CREATE DATABASE social;
USE social;

CREATE TABLE users(
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    fullname VARCHAR(60) NOT NULL,
    email VARCHAR(60) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
); 

CREATE TABLE perfil(
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    descripcion VARCHAR(100) NOT NULL,
    foto VARCHAR(255) NOT NULL

);